-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.datatype
(
    "Id" integer NOT NULL,
    "Name" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT datatype_pkey PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.item
(
    "ListId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "FieldChar01" character varying(1000) COLLATE pg_catalog."default",
    "FieldChar02" character varying(1000) COLLATE pg_catalog."default",
    "FieldInteger01" integer,
    "FieldoInteger02" integer,
    "FieldDecimal01" double precision,
    "FieldDecimal02" double precision,
    "FieldBoolean01" boolean,
    "FieldBoolean02" boolean,
    "FieldDatetime01" date,
    "FieldDatetime02" date,
    CONSTRAINT item_pkey PRIMARY KEY ("ListId", "ItemId")
);

CREATE TABLE IF NOT EXISTS public.list
(
    "Id" integer NOT NULL,
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT list_pkey PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.property
(
    "ListId" integer NOT NULL,
    "PropertySeq" integer NOT NULL,
    "Name" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "DataTypeId" integer NOT NULL,
    "FieldName" character(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT property_pkey PRIMARY KEY ("ListId", "PropertySeq")
);

ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT item_list FOREIGN KEY ("ListId")
    REFERENCES public.list ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.property
    ADD CONSTRAINT property_datatype FOREIGN KEY ("DataTypeId")
    REFERENCES public.datatype ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.property
    ADD CONSTRAINT property_list FOREIGN KEY ("ListId")
    REFERENCES public.list ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

